title: Seth Sylvester
logo: thumbnail.png
description: Professional Programmer. 
Adept at a multitude of programming languages. Specializes in video game development. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
